The flag 'directory' used in rule generatePlot is only valid for outputs, not inputs.
Building DAG of jobs...
Updating job 0 (run_after_checkpoint).
Using shell: /usr/bin/bash
Provided cores: 4
Rules claiming more threads will be scaled down.
Job counts:
	count	jobs
	1	generatePlot
	1	run_after_checkpoint
	2

[Fri May 15 23:18:54 2020]
rule generatePlot:
    input: data/results
    output: data/results/data.png
    jobid: 2

[Fri May 15 23:18:54 2020]
Error in rule generatePlot:
    jobid: 2
    output: data/results/data.png

RuleException:
CalledProcessError in line 176 of /home/dlcgold/stage-unimib/extra/snake/Snakefile:
Command 'set -euo pipefail;  /usr/bin/python /home/dlcgold/stage-unimib/extra/snake/.snakemake/scripts/tmp6iv7mkqa.generatePlot.py' returned non-zero exit status 1.
  File "/home/dlcgold/stage-unimib/extra/snake/Snakefile", line 176, in __rule_generatePlot
  File "/usr/lib/python3.8/concurrent/futures/thread.py", line 57, in run
Shutting down, this might take some time.
Exiting because a job execution failed. Look above for error message
Complete log: /home/dlcgold/stage-unimib/extra/snake/.snakemake/log/2020-05-15T231851.989637.snakemake.log
