Building DAG of jobs...
Updating job 0 (run_after_checkpoint).
Using shell: /usr/bin/bash
Provided cores: 4
Rules claiming more threads will be scaled down.
Job counts:
	count	jobs
	875	compareMem
	1	run_after_checkpoint
	876

[Fri May 15 21:18:23 2020]
rule compareMem:
    input: data/annotationsLessExon/ENSG00000183145.mem, data/annotations/ENSG00000183145.mem, data/annotationsLessExon/ENSG00000183145.gtf, data/annotations/ENSG00000183145.gtf
    output: data/results/ENSG00000183145.txt
    jobid: 3522
    wildcards: gene=ENSG00000183145

[Fri May 15 21:18:23 2020]
rule compareMem:
    input: data/annotationsLessExon/ENSG00000226527.mem, data/annotations/ENSG00000226527.mem, data/annotationsLessExon/ENSG00000226527.gtf, data/annotations/ENSG00000226527.gtf
    output: data/results/ENSG00000226527.txt
    jobid: 3641
    wildcards: gene=ENSG00000226527

[Fri May 15 21:18:23 2020]
rule compareMem:
    input: data/annotationsLessExon/ENSG00000234880.mem, data/annotations/ENSG00000234880.mem, data/annotationsLessExon/ENSG00000234880.gtf, data/annotations/ENSG00000234880.gtf
    output: data/results/ENSG00000234880.txt
    jobid: 4350
    wildcards: gene=ENSG00000234880

[Fri May 15 21:18:23 2020]
rule compareMem:
    input: data/annotationsLessExon/ENSG00000229962.mem, data/annotations/ENSG00000229962.mem, data/annotationsLessExon/ENSG00000229962.gtf, data/annotations/ENSG00000229962.gtf
    output: data/results/ENSG00000229962.txt
    jobid: 3970
    wildcards: gene=ENSG00000229962

[Fri May 15 21:18:23 2020]
Error in rule compareMem:
    jobid: 4350
    output: data/results/ENSG00000234880.txt

[Fri May 15 21:18:23 2020]
Error in rule compareMem:
    jobid: 3970
[Fri May 15 21:18:23 2020]
    output: data/results/ENSG00000229962.txt
Error in rule compareMem:

    jobid: 3641
[Fri May 15 21:18:23 2020]
    output: data/results/ENSG00000226527.txt
Error in rule compareMem:

RuleException:
URLError in line 167 of /home/dlcgold/stage-unimib/extra/snake/Snakefile:
<urlopen error [Errno 21] Is a directory: '/home/dlcgold/stage-unimib/extra/snake'>
  File "/home/dlcgold/stage-unimib/extra/snake/Snakefile", line 167, in __rule_compareMem
  File "/usr/lib/python3.8/urllib/request.py", line 222, in urlopen
  File "/usr/lib/python3.8/urllib/request.py", line 525, in open
  File "/usr/lib/python3.8/urllib/request.py", line 542, in _open
  File "/usr/lib/python3.8/urllib/request.py", line 502, in _call_chain
  File "/usr/lib/python3.8/urllib/request.py", line 1454, in file_open
  File "/usr/lib/python3.8/urllib/request.py", line 1493, in open_local_file
  File "/usr/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    jobid: 3522
    output: data/results/ENSG00000183145.txt
RuleException:
URLError in line 167 of /home/dlcgold/stage-unimib/extra/snake/Snakefile:
<urlopen error [Errno 21] Is a directory: '/home/dlcgold/stage-unimib/extra/snake'>
  File "/home/dlcgold/stage-unimib/extra/snake/Snakefile", line 167, in __rule_compareMem
  File "/usr/lib/python3.8/urllib/request.py", line 222, in urlopen
  File "/usr/lib/python3.8/urllib/request.py", line 525, in open
  File "/usr/lib/python3.8/urllib/request.py", line 542, in _open
  File "/usr/lib/python3.8/urllib/request.py", line 502, in _call_chain
  File "/usr/lib/python3.8/urllib/request.py", line 1454, in file_open
  File "/usr/lib/python3.8/urllib/request.py", line 1493, in open_local_file
  File "/usr/lib/python3.8/concurrent/futures/thread.py", line 57, in run
RuleException:
URLError in line 167 of /home/dlcgold/stage-unimib/extra/snake/Snakefile:
<urlopen error [Errno 21] Is a directory: '/home/dlcgold/stage-unimib/extra/snake'>
  File "/home/dlcgold/stage-unimib/extra/snake/Snakefile", line 167, in __rule_compareMem
  File "/usr/lib/python3.8/urllib/request.py", line 222, in urlopen
  File "/usr/lib/python3.8/urllib/request.py", line 525, in open
  File "/usr/lib/python3.8/urllib/request.py", line 542, in _open
  File "/usr/lib/python3.8/urllib/request.py", line 502, in _call_chain
  File "/usr/lib/python3.8/urllib/request.py", line 1454, in file_open
  File "/usr/lib/python3.8/urllib/request.py", line 1493, in open_local_file
  File "/usr/lib/python3.8/concurrent/futures/thread.py", line 57, in run

RuleException:
URLError in line 167 of /home/dlcgold/stage-unimib/extra/snake/Snakefile:
<urlopen error [Errno 21] Is a directory: '/home/dlcgold/stage-unimib/extra/snake'>
  File "/home/dlcgold/stage-unimib/extra/snake/Snakefile", line 167, in __rule_compareMem
  File "/usr/lib/python3.8/urllib/request.py", line 222, in urlopen
  File "/usr/lib/python3.8/urllib/request.py", line 525, in open
  File "/usr/lib/python3.8/urllib/request.py", line 542, in _open
  File "/usr/lib/python3.8/urllib/request.py", line 502, in _call_chain
  File "/usr/lib/python3.8/urllib/request.py", line 1454, in file_open
  File "/usr/lib/python3.8/urllib/request.py", line 1493, in open_local_file
  File "/usr/lib/python3.8/concurrent/futures/thread.py", line 57, in run
Shutting down, this might take some time.
Exiting because a job execution failed. Look above for error message
Complete log: /home/dlcgold/stage-unimib/extra/snake/.snakemake/log/2020-05-15T211819.372902.snakemake.log
